from app.exceptions.services.base import BaseServiceError


class AlreadyExistsServiceError(BaseServiceError):
    pass
